sudo: false

language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install flake8 ddt unittest2 renderspec requests
script:
  - flake8 renderspec tests/
  - python -m unittest discover tests/
